USE mariabd;
-- TRUNCATE TABLE empresa;
-- TRUNCATE TABLE cnae;
-- TRUNCATE TABLE simples;
-- TRUNCATE TABLE natju;
-- TRUNCATE TABLE pais;
-- TRUNCATE TABLE quals;
-- TRUNCATE TABLE motivos;
-- TRUNCATE TABLE munic;
-- TRUNCATE TABLE empresa;
-- TRUNCATE TABLE estabelecimento;
-- TRUNCATE TABLE socios;

-- Simples Nacional
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/F.K03200$W.SIMPLES.CSV' INTO TABLE simples CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- Domínios (Tabelas auxiliares)
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/F.K03200$Z.D51108.CNAECSV' INTO TABLE cnae CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/F.K03200$Z.D51108.MOTICSV' INTO TABLE motivos CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/F.K03200$Z.D51108.MUNICCSV' INTO TABLE munic CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/F.K03200$Z.D51108.NATJUCSV' INTO TABLE natju CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/F.K03200$Z.D51108.PAISCSV' INTO TABLE pais CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/F.K03200$Z.D51108.QUALSCSV' INTO TABLE quals CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;

-- BLOCO EMPRESAS (Y0 a Y9)
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y0.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y1.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y2.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y3.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y4.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y5.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y6.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y7.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y8.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
-- LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y9.D51108.EMPRECSV' INTO TABLE empresa CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
--
-- BLOCO SÓCIOS (Y0 a Y9)
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y0.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y1.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y2.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y3.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y4.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y5.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y6.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y7.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y8.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y9.D51108.SOCIOCSV' INTO TABLE socios CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
--
-- BLOCO ESTABELECIMENTOS CORRIGIDO (Y0 a Y9)
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y0.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y1.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y2.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y3.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y4.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y5.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y6.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y7.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y8.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
LOAD DATA LOCAL INFILE 'C:/ReceitaF/Extract/K3241.K03200Y9.D51108ESTABELE' INTO TABLE estabelecimento CHARACTER SET latin1 FIELDS TERMINATED BY ';' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 0 LINES;
